[package]
name = "ppm-writer"
version = "0.1.0"
edition = "2021"

[lib]
name = "ppm_writer"
path = "src/lib.rs"

[[bin]]
name = "ppmw"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
